import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "var(--surface)",
        surfaceDim: "var(--surface-dim)",
        surfaceBright: "var(--surface-bright)",
        surfaceContainerLowest: "var(--surface-container-lowest)",
        surfaceContainerLow: "var(--surface-container-low)",
        surfaceContainer: "var(--surface-container)",
        surfaceContainerHigh: "var(--surface-container-high)",
        surfaceContainerHighest: "var(--surface-container-highest)",
        onSurface: "var(--on-surface)",
        onSurfaceVariant: "var(--on-surface-variant)",
        inverseSurface: "var(--inverse-surface)",
        inverseOnSurface: "var(--inverse-on-surface)",
        outline: "var(--outline)",
        outlineVariant: "var(--outline-variant)",
        surfaceTint: "var(--surface-tint)",
        primary: "var(--primary)",
        onPrimary: "var(--on-primary)",
        primaryContainer: "var(--primary-container)",
        onPrimaryContainer: "var(--on-primary-container)",
        inversePrimary: "var(--inverse-primary)",
        secondary: "var(--secondary)",
        onSecondary: "var(--on-secondary)",
        secondaryContainer: "var(--secondary-container)",
        onSecondaryContainer: "var(--on-secondary-container)",
        tertiary: "var(--tertiary)",
        onTertiary: "var(--on-tertiary)",
        tertiaryContainer: "var(--tertiary-container)",
        onTertiaryContainer: "var(--on-tertiary-container)",
        error: "var(--error)",
        onError: "var(--on-error)",
        errorContainer: "var(--error-container)",
        onErrorContainer: "var(--on-error-container)",
        primaryFixed: "var(--primary-fixed)",
        primaryFixedDim: "var(--primary-fixed-dim)",
        onPrimaryFixed: "var(--on-primary-fixed)",
        onPrimaryFixedVariant: "var(--on-primary-fixed-variant)",
        secondaryFixed: "var(--secondary-fixed)",
        secondaryFixedDim: "var(--secondary-fixed-dim)",
        onSecondaryFixed: "var(--on-secondary-fixed)",
        onSecondaryFixedVariant: "var(--on-secondary-fixed-variant)",
        tertiaryFixed: "var(--tertiary-fixed)",
        tertiaryFixedDim: "var(--tertiary-fixed-dim)",
        onTertiaryFixed: "var(--on-tertiary-fixed)",
        onTertiaryFixedVariant: "var(--on-tertiary-fixed-variant)",
        background: "var(--background)",
        onBackground: "var(--on-background)",
        surfaceVariant: "var(--surface-variant)",
      },
      fontFamily: {
        sans: ["var(--font-noto-sans)", "var(--font-noto-sans-khmer)", "sans-serif"],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      }
    },
  },
  plugins: [],
};
export default config;
